services:
  supertube:
    build:
      context: .
      dockerfile: Dockerfile
    image: supertube:latest
    container_name: supertube
    stdin_open: true  # Enable stdin for interactive TUI
    tty: true         # Enable TTY for Textual
    environment:
      - TERM=xterm-256color
      - TZ=Europe/Brussels  # Set timezone to match host
    volumes:
      - ./config:/app/config     # Mount config directory (needs write access for token.pickle)
      - ./data:/app/data         # Mount data directory for SQLite cache
      - /etc/localtime:/etc/localtime:ro  # Mount host timezone
    restart: "no"  # Don't auto-restart (it's an interactive app)

  archiver:
    build:
      context: .
      dockerfile: Dockerfile
    image: supertube:latest
    container_name: supertube-archiver
    environment:
      - TZ=Europe/Brussels  # Set timezone to match host
    volumes:
      - ./config:/app/config     # Mount config directory (read-only for archiver)
      - ./data:/app/data         # Mount data directory for SQLite cache
      - /etc/localtime:/etc/localtime:ro  # Mount host timezone
    entrypoint: ["/bin/bash"]  # Override default entrypoint
    command:
      - -c
      - |
        apt-get update && apt-get install -y --no-install-recommends cron
        echo '0 3 * * * cd /app && python src/archiver_cron.py >> /app/data/archive.log 2>&1' > /etc/cron.d/supertube-archiver
        chmod 0644 /etc/cron.d/supertube-archiver
        crontab /etc/cron.d/supertube-archiver
        touch /var/log/cron.log
        cron && tail -f /var/log/cron.log
    restart: unless-stopped  # Auto-restart to ensure cron keeps running
